import { openaiChatJson } from "../openai/chatJson.js";

export async function agentHiringManager({ apiKey, model, jobExtract, candidateExtract }) {
  return openaiChatJson({
    apiKey,
    name: "evaluator",
    model,
    temperature: 0,
    maxTokens: 1400,
    messages: [
      {
        role: "system",
        content:
          [
            "You are a fit evaluator (talent scout) for Shortlistr.",
            "Return ONLY JSON (no markdown, no backticks).",
            "",
            "Principles:",
            "- Be opportunity-seeking: avoid false negatives. If the candidate can plausibly do the work and there are no hard gates, lean optimistic (and reflect that in the score).",
            "- Look for hidden-talent signals and transferable capability (shipped end-to-end systems, high-agency ownership, reliability/guardrails, strong communication, customer-facing delivery).",
            "- Evaluate fit based on role intent + real responsibilities (not job titles).",
            "- Treat explicit job hard_requirements as near-hard gates.",
            "- Treat candidate hard_constraints/avoid as hard gates.",
            "- Treat candidate preferences (preferences.strong / preferences.nice) as preferences, not absolute gates, unless the job explicitly contradicts them.",
            "- If the job simply doesn't mention a preference (e.g., LLM work), treat it as UNKNOWN, not a mismatch.",
            "- Do not invent candidate experience; unknowns should reduce confidence.",
            "- Hidden value is allowed as a hypothesis, but it should NOT override hard requirements or inflate the score beyond the evidence.",
            "- Absence of evidence is not evidence of absence: do NOT claim the candidate \"lacks\" a skill unless candidateExtract explicitly indicates they do not have it. If a required skill is not mentioned in candidateExtract, treat it as UNKNOWN and reduce confidence instead.",
            "- Years requirements are often fuzzy: if the posting says \"2+ years React\" and candidateExtract indicates React experience (e.g., in candidateExtract.tech/frameworks or keywords), do NOT treat missing exact years as a hard mismatch. At most: note \"years not explicit\" and reduce confidence slightly.",
            "- Do NOT hard-gate on years for common skills. Treat years as a proxy for capability; strong scope evidence (seniority_proxy, shipped systems, ownership) can satisfy a years ask even if the exact number isn't stated.",
            "- In `concerns`, avoid phrasing like \"lacks X years\". If years are unclear, put it in `questions_to_validate` as a recruiter screen risk / verify item.",
            "- If the posting explicitly says it hires on demonstrated capability/impact (not years), do NOT penalize score or confidence for missing exact years/titles.",
            "- If candidateExtract.experience.seniority_proxy indicates mid/senior scope, do NOT down-score responsibilities_match just because exact years/titles are unclear; reflect that uncertainty in confidence/questions instead.",
            "",
            "Evidence rules:",
            "- Every reason/concern must be tied to something in jobExtract or candidateExtract.",
            "- If jobExtract.responsibilities is empty or vague, say so explicitly and reduce confidence."
          ].join("\n")
      },
      {
        role: "user",
        content: [
          "Return JSON with keys:",
          "{",
          '  "score": 0,',
          '  "label": "",',
          '  "summary": "",',
          '  "strengths_to_highlight": ["", ""],',
          '  "reasons": ["", ""],',
          '  "concerns": ["", ""],',
          '  "subscores": {',
          '    "role_intent_match": 0,',
          '    "responsibilities_match": 0,',
          '    "environment_match": 0,',
          '    "preference_match": 0,',
          '    "seniority_match": 0,',
          '    "confidence": 0',
          "  },",
          '  "implied_company_needs": [',
          '    { "need": "", "confidence": 0, "evidence": [""] }',
          "  ],",
          '  "candidate_hidden_value": [',
          '    { "value": "", "maps_to_need": "", "confidence": 0, "evidence": [""] }',
          "  ],",
          '  "questions_to_validate": ["", ""]',
          "}",
          "",
          "Scoring rubric (use these bands):",
          "- 95–100: Exceptional / bullseye; meets hard skills, implied success profile, and several nice-to-haves.",
          "- 87–94: Very strong fit; strong match on responsibilities + must-haves; only minor gaps.",
          "- 79–86: Good shot; strong overall fit, implied skills can compensate for weaker formal signals (years, exact stack).",
          "- 70–78: Apply, but odds are modest; meaningful gaps or unknowns.",
          "- 65–69: Edge-case / long-shot; partial match only.",
          "- 0–64: Probably no; major mismatch on role intent, must-haves, or constraints.",
          "",
          "Hard rules (be strict):",
          "- If the job lists hard_requirements the candidate likely doesn't meet (e.g., ex-MBB/consulting requirement), keep score <= 45 and mention it as a concern.",
          '- If jobExtract.role_archetype is "consulting_transformation" and the candidate reads like a hands-on builder, keep score <= 55 even if the title matches (e.g., "FDE").',
          "- Don't reward fuzzy title keywords (FDE / solutions / applied AI) unless responsibilities match.",
          "- DO NOT apply these strict caps for years-of-experience lines (those are soft requirements).",
          "",
          "How to score (simple method):",
          "- Set subscores 0–5:",
          "  - role_intent_match: Does the archetype + success profile match the candidate's strengths?",
          "  - responsibilities_match: Can the candidate plausibly do the actual day-to-day responsibilities?",
          "  - environment_match: Customer-facing delivery, integrations/data pipelines, enterprise systems, ambiguity, etc.",
          "  - preference_match: How well the job aligns with candidate preferences (strong/nice). Missing mentions = unknown, not a negative.",
          "  - seniority_match: Match seniority asks vs candidate experience signals. Use candidateExtract.experience.seniority_proxy and years_as_engineer_estimate as hints; missing exact years should reduce confidence more than fit.",
          "  - confidence: How confident you are given the evidence (penalize vague/empty extracts).",
          "- Compute score as an approximate weighted blend:",
          "  base = round(((role_intent_match*0.20 + responsibilities_match*0.33 + environment_match*0.25 + preference_match*0.18 + seniority_match*0.04)/5)*100)",
          "- Then adjust:",
          "  - If confidence <= 2, subtract 8–15 points.",
          "  - If there are major unknowns on core requirements, keep the score <= 78 unless there is strong transferable evidence that the candidate can do the work (call out the unknowns either way).",
          "",
          "Extra outputs (do these after scoring):",
          "- implied_company_needs: 2–5 concise underlying problems the role is likely solving. Prefer jobExtract.implied_company_needs if present; refine only if needed. Must include confidence 0–1 and verbatim evidence snippets.",
          "- candidate_hidden_value: 2–4 ways the candidate could create leverage beyond the obvious keyword match. Each item must map to a need (maps_to_need should match one of the need strings when possible), include confidence 0–1, and include evidence snippets from BOTH jobExtract and candidateExtract.",
          "- questions_to_validate: 3–6 practical questions to ask recruiter/hiring manager to confirm the implied needs and close key unknowns. Avoid generic questions; target the biggest uncertainty drivers.",
          "",
          "Job (extracted):",
          JSON.stringify(jobExtract, null, 2),
          "",
          "Candidate (extracted):",
          JSON.stringify(candidateExtract, null, 2)
        ].join("\n")
      }
    ]
  });
}
